plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.mycallerid'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.mycallerid"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    
    // YAHAN FIX HAI: Java aur Kotlin dono ko Version 17 par set kar diya
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Firebase Realtime Database
    implementation 'com.google.firebase:firebase-database-ktx:20.3.0'
}